name: multi_video_player_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  appinio_video_player: ^1.2.2
  awesome_video_player: ^1.0.5
  bitmovin_player: ^0.19.0
  fijkplayer: ^0.11.0
  flick_video_player: ^0.9.0
  flutter_hls_video_player: ^1.0.1
  flutter_playout: ^2.0.1
  flutter_vlc_player: ^7.4.3
  lecle_yoyo_player: ^0.0.8
  native_video_player: ^4.0.0
  omni_video_player: ^2.0.5
  pod_player: ^0.2.2
  video_js_player: ^0.0.18
  video_player: ^2.10.0
  video_player_pip: ^0.0.10
  video_view: ^1.1.4
  chewie: ^1.12.1
  go_router: ^16.1.0
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  sliver_tools: ^0.2.12
  gap: ^3.0.1
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  equatable: ^2.0.7
  audio_session: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  go_router_builder: ^3.0.1
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
